language: python
addons:
  apt:
    packages:
      - latexmk
      - texlive
      - texlive-xetex
      # - pdflatex
python:
  - "3.6"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/test/
    - $TRAVIS_BUILD_DIR/src/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - elan toolchain install 3.4.2
  - elan default 3.4.2
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  # - ./purge_olean.sh
  # - rm mathlib.txt || true
  # - pip3 install python3-venv
  # - pip install --user travis-sphinx
  - make install-deps
  - export PATH=$HOME/.local/bin:$PATH


script:
  - make html
  - make latexpdf
  # - make leantest
